version: 2.1

executors:
  sb_node:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'large', 'xlarge']
        default: 'medium'
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:10-browsers
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: <<parameters.class>>
  sb_node_12:
    parameters:
      class:
        description: The Resource class
        type: enum
        enum: ['small', 'medium', 'large', 'xlarge']
        default: 'medium'
    working_directory: /tmp/storybook
    docker:
      - image: circleci/node:12-browsers
        environment:
          NODE_OPTIONS: --max_old_space_size=4096
    resource_class: <<parameters.class>>

jobs:
  build:
    executor:
      class: large
      name: sb_node
    steps:
      - checkout
      - restore_cache:
          key: v1-storybookjs-native-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - "node_modules"
            - "packages/native-addon/node_modules"
            - "packages/native/node_modules"
          key: v1-storybookjs-native-{{ arch }}-{{ checksum "yarn.lock" }}

  test:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Test
          command: yarn test
  lint:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: yarn lint
  release:
    executor: sb_node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Assume Github Role
          command: 'git config --global user.email "lshadler13@gmail.com" && git config --global user.name "lshadler"'
      - run:
          name: Auto Shipit
          command: |
            yarn release
workflows:
  test:
    jobs:
      - build
      - lint:
          requires:
            - build            
      - test:
          requires:
            - build
      - release:
          requires:
            - test
            - lint          